### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by Leven-Cheung** [openxrlab/xrdslam#5]
When I try to run nice-slam and point-slam, this situation will happen.The detail of this error is :

> Traceback (most recent call last):
  File "/mnt/15disk2/zgz/anaconda/envs/xrdslam1/bin/ds-run", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/15disk2/zgz/slam/xrdslam/scripts/run.py", line 28, in entrypoint
    main(
  File "/mnt/15disk2/zgz/slam/xrdslam/scripts/run.py", line 22, in main
    slam.setup()
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/engine/xrdslamer.py", line 55, in setup
    self.slam = self.config.xrdslam.setup()
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/configs/base_config.py", line 37, in setup
    return self._target(self, **kwargs)
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/pipeline/xrdslam.py", line 52, in __init__
    self.algorithm = manager.ShareAlgorithm(config=self.config.algorithm,
  File "/mnt/15disk2/zgz/anaconda/envs/xrdslam1/lib/python3.10/multiprocessing/managers.py", line 723, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/mnt/15disk2/zgz/anaconda/envs/xrdslam1/lib/python3.10/multiprocessing/managers.py", line 608, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
  File "/mnt/15disk2/zgz/anaconda/envs/xrdslam1/lib/python3.10/multiprocessing/managers.py", line 93, in dispatch
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/15disk2/zgz/anaconda/envs/xrdslam1/lib/python3.10/multiprocessing/managers.py", line 209, in _handle_request
    result = func(c, *args, **kwds)
  File "/mnt/15disk2/zgz/anaconda/envs/xrdslam1/lib/python3.10/multiprocessing/managers.py", line 387, in create
    obj = callable(*args, **kwds)
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/algorithms/point_slam.py", line 77, in __init__
    self.model = model_config.setup(camera=camera)
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/configs/base_config.py", line 37, in setup
    return self._target(self, **kwargs)
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/models/conv_onet_pointslam.py", line 85, in __init__
    super().__init__(config=config,
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/models/base_model.py", line 40, in __init__
    self.populate_modules()  # populate the modules
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/models/conv_onet_pointslam.py", line 94, in populate_modules
    self.load_pretrain()
  File "/mnt/15disk2/zgz/slam/xrdslam/slam/models/conv_onet_pointslam.py", line 234, in load_pretrain
    ckpt = torch.load(self.config.pretrained_decoders_middle_fine,
  File "/mnt/15disk2/zgz/anaconda/envs/xrdslam1/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/mnt/15disk2/zgz/anaconda/envs/xrdslam1/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

but it is good running when using co-slam and vox-fusion.I searched that and Chatgpt said it might be something wrong in pre-trained files. Am I doing something wrong?

**Comment by wangxiaomeng030** [comment]
Could you please check if the downloaded pre-trained model is complete? You can download it from the zip file and replace it.

**Comment by wangxiaomeng030** [comment]
Here is a download link for the pre-trained model of xrdslam： https://drive.google.com/file/d/14aro7iugO6ey62iVpXrVAXLTzP6Ned3L/view?usp=drive_link

**Comment by Leven-Cheung** [comment]
This problem is solved, thank you very much, I guess it is probably caused by the network wall that can not use GLFS.Thank you for your help
