### ISSUE TITLE
Transformation inconsistency detected!

### ISSUE THREAD

**Issue by DY-ATL** [openxrlab/xrdslam#8]
[17:43:42] Saving config to: outputs/config.yml                                                          xrdslamer.py:41
  0%|                                                                                                                                                                                  | 0/2000 [00:00<?, ?it/s]Backend tkagg is interactive backend. Turning interactive mode on.
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
  0%|                                                                                                                                                                                  | 0/2000 [01:31<?, ?it/s]
Process Process-3:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/xrdslam/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda3/envs/xrdslam/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/Code/xrdslam/slam/pipeline/tracker.py", line 97, in spin
    current_frame = Frame(fid=idx_np,
  File "/home/ubuntu/Code/xrdslam/slam/common/frame.py", line 44, in __init__
    raise ValueError(error_message, pose, self.pose.matrix())
ValueError: ('Transformation inconsistency detected!', tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], requires_grad=True), tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], grad_fn=<CopySlices>))

In slam/pipeline/tracker.py:L62, I found the value returned by the __getitem__() function is correct. The value from the dataloader becomes all 0, but the tensor shape is still there. What is the reason?

**Comment by DY-ATL** [comment]
I change the  num_workers=0. Problem solved.
        pbar = tqdm(
            DataLoader(self.dataset,
                       batch_size=1,
                       shuffle=False,
                       num_workers=0))
